### ISSUE TITLE
TODOs for next build

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/tensorflow-feedstock#175]
Since rebuilding takes so much effort and we don't do it that often, I wanted to create an issue to track the various things we should adapt for the next build:
- [ ] bump to [tensorflow 2.7.0](https://github.com/tensorflow/tensorflow/issues/50204)
- [ ] remove bazel-workarounds that should now be taken care of in `bazel-toolchain` (see https://github.com/conda-forge/bazel-toolchain-feedstock/pull/5)
- [ ] next gprc migration:
  - https://github.com/conda-forge/tensorflow-feedstock/pull/171
  - https://github.com/conda-forge/tensorflow-feedstock/pull/173
- [ ] Add `cudatoolkit` as a dependency to `tensorflow`, or even better, get rid of `tensorflow-base` (since it's not needed anymore now that `tf-estimator` is built in this feedstock), see https://github.com/conda-forge/tensorflow-feedstock/issues/162
  - note that "getting rid" means in terms of the core recipe, there could/should still be a compatibility output for existing users in that case.
- [ ] Loosen package pinnings where possible, see #151 
  - [ ] In particular, `numpy` has been unpinned from 1.19.2 in TF 2.7 as of https://github.com/tensorflow/tensorflow/commit/a90383a867a2337600c775d67842f308da9d118b
- [ ] Add a run-depend on `__cuda` virtual package or the GPU builds, see #174 
- [ ] Python 3.10 builds? The migrator is currently failing to resolve the builds, probably not least due to the tight package pinnings (and there being no numpy 1.19 for cpython 3.10).

CC @hmaarrfk @xhochy @wolfv @conda-forge/tensorflow, feel free to add more things in the description. If any of those points end up being a huge hassle, it can of course be pushed off to the build after that.

Anyone is welcome to chime in if I forgot something. 🙃

**Comment by njzjz** [comment]
Currently tensorflow here is not built against MKL (OneDNN), but do we plan to?

**Comment by h-vetinari** [comment]
> Currently tensorflow here is not built against MKL (OneDNN), but do we plan to?

Not sure how involved this is, but since onednn [seems](https://github.com/conda-forge/onednn-feedstock) to be available for all relevant platforms, I'm not opposed to trying!

**Comment by xhochy** [comment]
Tensorflow is building oneDNN from source in the build currently. That is probably the first 1-2h of CI. Getting that from the feedstock instead of building from source would help a lot.

**Comment by h-vetinari** [comment]
> Tensorflow is building oneDNN from source in the build currently. That is probably the first 1-2h of CI. Getting that from the feedstock instead of building from source would help a lot.

That sounds like a big win if we can pull it off!
