### ISSUE TITLE
tracking "easy" updates and improvements (for patch release 2.8.1?)

### ISSUE THREAD

**Issue by ngam** [conda-forge/tensorflow-feedstock#234]
### Comment:

We should do these in a build right after 2.8.0 (there will likely be 2.8.1 and 2.9.0 very soon). Feel free to edit and add the other outstanding migrations. I believe the ones below are relatively straightforward (the xla one may add some time to the compilation, but we will see)
- [x] #230: incorporate `${CPU_COUNT}`
- [x] #223: add xla support
- [ ] #206: add tf-io

**Comment by ngam** [comment]
Note: tf-io should be done separately. It is complicated...
